### PR TITLE
Mentions of "unthreaded" replaced with "single-threaded"

### PR DESCRIPTION
**Pull request by patilatharva**
Replacing 'unthreaded' with 'single-threaded' in all variables and comments, to be consistent with the `single-threaded` LF PR: https://github.com/lf-lang/lingua-franca/pull/1817.

Note: to be merged after the main `single-threaded` PR.

### CODE REVIEW

**Review by lhstrh — COMMENTED** [review]
This looks fine to me -- will merge right ahead of https://github.com/lf-lang/lingua-franca/pull/1817

**Comment by erlingrj** [comment]
@lhstrh, conflicts are now resolved

**Comment by lhstrh** [comment]
Thanks, @erlingrj!

**Review by lhstrh — APPROVED** [review]
:+1:

**Pull request merged**
