### PR TITLE
Fix Unintended Action Override

### PR DESCRIPTION
**Pull request by Depetrol**
This PR fixes the unintended action override when two actions are triggered at about the same time in issue #489. The bug was in `convert_C_action_to_py`, the token value in the trigger is suspectable to concurrency overrides. The solution was to use the token value in the action. The companion PR in lingua-franca is https://github.com/lf-lang/lingua-franca/pull/2423

### CODE REVIEW

**Comment by erlingrj** [comment]
Could you explain how the race condition occurs, i.e. what is the sequence of events causing it. Also what exactly is this change doing?

**Comment by erlingrj** [comment]
Well done on tracking it down BTW!

**Comment by Depetrol** [comment]
Also huge thanks to @edwardalee and @erlingrj for helping me look into this!

**Comment by Depetrol** [comment]
Not sure why the windows tests are failing -- this seems unrelated to the change in this PR since tests are also failing in the main branch.

**Review by edwardalee — APPROVED** [review]
Wow, great catch! Indeed, using the template token is not safe, so this looks like the right fix to me!

**Review by erlingrj — APPROVED** [review]
Great find Shulu! I think we can safely merge this and address Windows issues separately

**Comment by Depetrol** [comment]
`reactor-c` requires that all tests pass before merging, so we might have to wait for https://github.com/lf-lang/lingua-franca/pull/2424 to me merged.

**Comment by Depetrol** [comment]
There is another concurrency bug that is triggered probabilistically with the newly introduced test `ConcurrentAction.lf`. Running the test 20 times could trigger the bug quite consistently.

**Comment by Depetrol** [comment]
Since the newly introduced test in https://github.com/lf-lang/lingua-franca/pull/2423 has been marked as failing in https://github.com/lf-lang/lingua-franca/pull/2422, the checks are passing and automatic merge was triggered. I'll start another PR for the other concurrency bug.

**Pull request merged**
