### PR TITLE
Critical sections enabled outside of the context of a reactor

### PR DESCRIPTION
**Pull request by edwardalee**
This PR makes it possible for users to enter and exit critical sections and access time both inside and outside of the context of a reactor.  This enables resurrecting the MQTT examples in the example repo.

This has a [companion PR](https://github.com/lf-lang/lingua-franca/pull/1901) in lingua-franca.

### CODE REVIEW

**Comment by petervdonovan** [comment]
My understanding is that one of the key objectives of LF is to allow users to avoid the explicit use of mutexes/critical sections.

I assume that the MQTT example that you refer to is [this file](https://github.com/lf-lang/examples-lingua-franca/blob/f851ad6357a2dbaa43f2451de87ac6a2ab346287/C/src/mqtt/lib/MQTTPublisher.lf), where a mutex is acquired while accessing the MQTT API, presumably because the MQTT API is not thread-safe. If this is the case, then why not enforce mutual exclusion of accesses to the MQTT API by requiring all accesses to the MQTT API to be performed within the same reactor instance?

In order for this approach to work, it would be necessary for reactors to pass various arguments along to the MQTT reactor, and the MQTT reactor would have to pass back any handles and outputs that it gets from the API, and everything would have to be wired to that one reactor, and altogether it would make for a cumbersome way to access a simple C API. However, I think that we should consider this approach anyway because doing so would draw attention to the areas where the LF language could be improved. If the standard way of using LF is to use it to structure an application but to resort to explicit critical sections as soon as it becomes inconvenient to use LF to avoid concurrency bugs, then LF applications will not be safer than applications written in popular general-purpose languages.

**Comment by erlingrj** [comment]
I agree with what you are writing, @petervdonovan. But there might still be reasons for exposing the platform API to the users. They might want to synchronize an async context in a `lf_thread_t` with either another `lf_thread_t` or with a reactor. We earlier had some debate on this here: https://github.com/lf-lang/reactor-c/issues/161

**Review by petervdonovan — APPROVED** [review]
OK, I will not belabor a point that has already been discussed. I am satisfied with having commented that the particular use of critical sections in the MQTT examples may not be appropriate.

**Comment by edwardalee** [comment]
I think @petervdonovan 's suggestion regarding MQTT is a really good one and it may not be all that hard to implement. But I also agree with @erlingrj that at least having the possibility of accessing those functions is OK.  We don't have to encourage it, but might lead to some interesting innovations.  Maybe @petervdonovan could open an issue in the examples repo to redesign the MQTT code?

**Pull request merged**
