### PR TITLE
Make improvements on CMake

### PR DESCRIPTION
**Pull request by erlingrj**
Mainly changing how reactor-c corelib is built. Originally it used `add_subdirectory` to add platform, modal, threaded and utils sources. This is a bit hacky since it creates new node and compile definitions and sources can not easily be added to the parent node. Now I use `include` instead. Needed some additional changes for this to work.

### CODE REVIEW

**Comment by erlingrj** [comment]
Btw, @petervdonovan can you immediately see why the CI is not running on my PRs?

**Comment by petervdonovan** [comment]
No, I'm not sure why not. I think that sometimes one has to merge master into the branch in order to trigger CI.

**Review by petervdonovan — APPROVED** [review]
This looks good to merge. Thanks for the cleanup!

**Comment by erlingrj** [comment]
OK. Just have to fix the CI.  @lhstrh. There is something wrong with the CI see here: https://github.com/lf-lang/reactor-c/actions/runs/3864134424/workflow

image

Do you understand anything of this?

**Comment by petervdonovan** [comment]
Oh, I get it now. Dongha just forgot to change from `auth` back to `master` when merging #105, and the `auth` branch in `lingua-franca` has since been deleted. So if, in this PR, we just change `auth` back to `master` in `reactor-c/.github/workflows/ci.yml`, it should be fine again.

**Pull request merged**
